### PR TITLE
Removed some warnings clogging up the log file.

### PR DESCRIPTION
**Pull request by ronnymn**
Added empty array as default for get_option cuws_hide_admin_columns to
avoid warnings form subsequent in_array checks.

### CODE REVIEW

**Comment by senlin** [comment]
Hi @ronnymn thanks for your pull request, can you please explain what it for exactly? I'm afraid I don't really understand.

**Comment by ronnymn** [comment]
Hi

I am currenty developing on a site where you plugin is active. In the
debug.log we were getting a lot of lines with warnings. So to eliminate the
problem I wrote a small change,
The problem was the get_option that returned false becaus no option was
set. So by giving it an emty array as default the in_array checks does not
give any warnings.


[25-Feb-2016 23:13:25 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 258
[25-Feb-2016 23:13:25 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 262
[25-Feb-2016 23:13:25 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 267
[25-Feb-2016 23:13:25 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 272
[25-Feb-2016 23:13:25 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 277
[25-Feb-2016 23:13:36 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 258
[25-Feb-2016 23:13:36 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 262
[25-Feb-2016 23:13:36 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 267
[25-Feb-2016 23:13:36 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 272
[25-Feb-2016 23:13:36 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 277
[25-Feb-2016 23:13:52 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 258
[25-Feb-2016 23:13:52 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 262
[25-Feb-2016 23:13:52 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 267
[25-Feb-2016 23:13:52 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 272
[25-Feb-2016 23:13:52 Europe/Oslo] PHP Warning:  in_array() expects
parameter 2 to be array, boolean given in /home/pronav/www/
www.pronav.no/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php
on line 277


Vennlig hilsen,

*Ronny Myhre Njaastad*

Systemutvikler

ronny@maksimer.no
M.   +47 900 66 303

[image: Beskrivelse: Maksimer Logo]
www.maksimer.no
www.twitter.com/maksimer

2016-02-26 3:25 GMT+01:00 Piet Bos <notifications@github.com>:

**Comment by senlin** [comment]
Ah okay, I understand better now, thanks for your explanation. And for the PR of course, I will merge it now and release an updated version soon.

**Comment by senlin** [comment]
Ronny, may I ask, would you have any idea on how to solve issue #4 on Multisite Support. It already has gotten better than before, but perhaps it could be made even better? what do you think?

**Comment by ronnymn** [comment]
Just took a quick glance at it now. It would probably be a good thing if
you looped through the "_set_defaults" method for each individual site.




Vennlig hilsen,

*Ronny Myhre Njaastad*

Systemutvikler

ronny@maksimer.no
M.   +47 900 66 303

[image: Beskrivelse: Maksimer Logo]
www.maksimer.no
www.twitter.com/maksimer

2016-02-26 11:36 GMT+01:00 Piet Bos <notifications@github.com>:

**Comment by senlin** [comment]
Cool, thanks Ronny, I will look into that.

Cheers,
Piet
On February 26, 2016 at 19:08:23, Ronny Myhre Njaastad (notifications@github.com) wrote:

Just took a quick glance at it now. It would probably be a good thing if
you looped through the "_set_defaults" method for each individual site.




Vennlig hilsen,

*Ronny Myhre Njaastad*

Systemutvikler

ronny@maksimer.no
M. +47 900 66 303

[image: Beskrivelse: Maksimer Logo]
www.maksimer.no
www.twitter.com/maksimer

2016-02-26 11:36 GMT+01:00 Piet Bos <notifications@github.com>:

**Pull request merged**
